const dummyData = {
    categories: [
        { name: "Hot Coffee", description: "Freshly brewed hot coffee drinks" },
        { name: "Cold Coffee", description: "Chilled and iced coffee beverages" },
        { name: "Espresso", description: "Strong and rich espresso-based drinks" },
        { name: "Frappuccino", description: "Blended frozen coffee delights" },
        { name: "Tea & Matcha", description: "Soothing teas and matcha drinks" },
        { name: "Pastries & Snacks", description: "Freshly baked pastries and light bites" },
    ],

    customizations: [
        // Milk options
        { name: "Oat Milk", price: 500, type: "milk" },
        { name: "Almond Milk", price: 500, type: "milk" },
        { name: "Soy Milk", price: 400, type: "milk" },
        { name: "Full Cream Milk", price: 300, type: "milk" },

        // Syrups
        { name: "Vanilla Syrup", price: 300, type: "syrup" },
        { name: "Caramel Syrup", price: 300, type: "syrup" },
        { name: "Hazelnut Syrup", price: 350, type: "syrup" },
        { name: "Brown Sugar Syrup", price: 300, type: "syrup" },

        // Extras
        { name: "Extra Espresso Shot", price: 600, type: "extra" },
        { name: "Whipped Cream", price: 400, type: "extra" },
        { name: "Cinnamon Dust", price: 200, type: "extra" },
        { name: "Cocoa Powder", price: 200, type: "extra" },
        { name: "Sea Salt Foam", price: 500, type: "extra" },

        // Size upgrades
        { name: "Upsize to Large", price: 500, type: "size" },
        { name: "Upsize to XL", price: 900, type: "size" },
    ],

    menu: [
        {
            name: "Classic Americano",
            description: "Bold espresso diluted with hot water for a clean, strong cup",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Americano-removebg-preview.png",
            price: 2500,
            rating: 4.5,
            is_available: true,
            category_name: "Hot Coffee",
            customizations: ["Extra Espresso Shot", "Vanilla Syrup", "Upsize to Large", "Upsize to XL"],
        },
        {
            name: "Flat White",
            description: "Smooth microfoam milk poured over a rich double ristretto shot",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Flat_White_Coffee-removebg-preview.png",
            price: 3200,
            rating: 4.7,
            is_available: true,
            category_name: "Hot Coffee",
            customizations: ["Oat Milk", "Almond Milk", "Vanilla Syrup", "Extra Espresso Shot"],
        },
        {
            name: "Caramel Latte",
            description: "Espresso and steamed milk topped with rich caramel drizzle",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Caramel_Latte-removebg-preview.png",
            price: 3800,
            rating: 4.8,
            is_available: true,
            category_name: "Hot Coffee",
            customizations: ["Caramel Syrup", "Oat Milk", "Whipped Cream", "Extra Espresso Shot", "Upsize to Large"],
        },
        {
            name: "Double Espresso",
            description: "Two concentrated shots of premium espresso, intense and aromatic",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Double_Espresso-removebg-preview.png",
            price: 2200,
            rating: 4.6,
            is_available: true,
            category_name: "Espresso",
            customizations: ["Extra Espresso Shot", "Vanilla Syrup", "Brown Sugar Syrup"],
        },
        {
            name: "Cortado",
            description: "Equal parts espresso and warm milk to balance the acidity",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Cortado-removebg-preview.png",
            price: 2800,
            rating: 4.4,
            is_available: true,
            category_name: "Espresso",
            customizations: ["Oat Milk", "Soy Milk", "Vanilla Syrup", "Cinnamon Dust"],
        },
        {
            name: "Iced Brown Sugar Latte",
            description: "Cold espresso with brown sugar syrup, shaken over ice with oat milk",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Brown_Sugar_Shaken_Espresso-removebg-preview.png",
            price: 4200,
            rating: 4.9,
            is_available: true,
            category_name: "Cold Coffee",
            customizations: ["Brown Sugar Syrup", "Oat Milk", "Extra Espresso Shot", "Upsize to Large", "Upsize to XL"],
        },
        {
            name: "Cold Brew",
            description: "Slow-steeped 18-hour cold brew, smooth and low acidity",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Cold_Brew-removebg-preview.png",
            price: 3800,
            rating: 4.7,
            is_available: true,
            category_name: "Cold Coffee",
            customizations: ["Vanilla Syrup", "Caramel Syrup", "Full Cream Milk", "Upsize to Large"],
        },
        {
            name: "Iced Hazelnut Cappuccino",
            description: "Chilled espresso with hazelnut syrup and cold foam",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Hazelnut_Iced_Coffee-removebg-preview.png",
            price: 4500,
            rating: 4.6,
            is_available: true,
            category_name: "Cold Coffee",
            customizations: ["Hazelnut Syrup", "Almond Milk", "Whipped Cream", "Extra Espresso Shot"],
        },
        {
            name: "Caramel Frappuccino",
            description: "Blended iced coffee with caramel, topped with whipped cream",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Caramel_Frappuccino-removebg-preview.png",
            price: 5000,
            rating: 4.8,
            is_available: true,
            category_name: "Frappuccino",
            customizations: ["Caramel Syrup", "Whipped Cream", "Extra Espresso Shot", "Upsize to Large", "Upsize to XL"],
        },
        {
            name: "Mocha Frappuccino",
            description: "Rich chocolate blended with espresso and milk over ice",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Mocha_Frappes-removebg-preview.png",
            price: 5200,
            rating: 4.7,
            is_available: true,
            category_name: "Frappuccino",
            customizations: ["Cocoa Powder", "Whipped Cream", "Oat Milk", "Extra Espresso Shot"],
        },
        {
            name: "Matcha Latte",
            description: "Ceremonial grade matcha whisked with steamed milk",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Mocha_Frappes-removebg-preview.png",
            price: 4000,
            rating: 4.5,
            is_available: true,
            category_name: "Tea & Matcha",
            customizations: ["Oat Milk", "Almond Milk", "Vanilla Syrup", "Whipped Cream", "Upsize to Large"],
        },
        {
            name: "Chai Tea Latte",
            description: "Spiced black tea concentrate with steamed milk and cinnamon",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Chai_Tea_Latte-removebg-preview.png",
            price: 3500,
            rating: 4.3,
            is_available: true,
            category_name: "Tea & Matcha",
            customizations: ["Oat Milk", "Brown Sugar Syrup", "Cinnamon Dust", "Upsize to Large"],
        },
        {
            name: "Butter Croissant",
            description: "Flaky, golden-baked French-style butter croissant",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Croissant_Butter-removebg-preview.png",
            price: 2000,
            rating: 4.6,
            is_available: true,
            category_name: "Pastries & Snacks",
            customizations: [],
        },
        {
            name: "Blueberry Muffin",
            description: "Soft moist muffin bursting with fresh blueberries",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Blueberry_Muffins-removebg-preview.png",
            price: 2200,
            rating: 4.4,
            is_available: true,
            category_name: "Pastries & Snacks",
            customizations: [],
        },
        {
            name: "Sea Salt Cold Brew",
            description: "Cold brew topped with a silky sea salt cream foam",
            image_url: "https://zwe-clipcast.b-cdn.net/coffee-rm-bg/Cold_brew_sea-removebg-preview.png",
            price: 4800,
            rating: 4.9,
            is_available: false,
            category_name: "Cold Coffee",
            customizations: ["Sea Salt Foam", "Brown Sugar Syrup", "Upsize to Large", "Upsize to XL"],
        },
    ],
};

export default dummyData;